apiVersion: v1
kind: Pod
metadata:
  name: writer-pod
spec:
  containers:
    - name: writer
      image: busybox
      command: ["/bin/sh", "-c"]
      args: 
        - | 
          echo "Data Written at $(date)" > /data/output
          echo "Pod Name: writer-pod " >> /data/output
          cat /data/output
          sleep 3600
      volumeMounts: 
        - name: app-storage
          mountPath: /data
  volumes: 
    - name: app-storage
      persistentVolumeClaim:
        claimName: app-storage