apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: app-storage
spec:
  accessModes:
    - ReadWriteOnce # One Pod can read and write at a time
  resources: 
    requests:
      storage: 100Mi # how much storage you need
  storageClassName:
