apiVersion: v1
kind: ConfigMap
metadata:
  name: flask-config
data:
  APP_ENV: "staging"
  DB_HOST: "postgres-staging.internal"
  LOG_LEVEL: "debug"
---
apiVersion: v1
kind: Pod
metadata:
  name: flask-app
spec:
  containers:
    - name: flask
      image: flask-configmap-demo:v1
      imagePullPolicy: Never        # use local image, don't pull from registry
      envFrom:
        - configMapRef:
            name: flask-config
      ports:
        - containerPort: 5000