apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-custom-config
data: 
  nginx.conf: |
    events {}
    http {
      server {
      listen 80;
      location / {
        return 200 'ConfigMap is working\n'
        add_header Content-Type text/plain
      }
      location /health {
        return 200 'healthy\n';
        add_header Content-Type text/plain
      }
     } 
    }

---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-custom
spec:
  containers:
    - name: web
      image: nginx:1.25
      volumeMounts:
        - name: nginx-conf
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf           # Mount single file, not whole directory
  volumes:
    - name: nginx-conf
      configMap:
        name: nginx-custom-config