apiVersion: v1
kind: Pod
metadata:
  name: my-first-pod
  labels: 
    app: demo
    env: learning 
spec:
  containers: 
    - name: web
      image: nginx:1.25
      ports:
        - containerPort: 80