apiVersion: v1
kind: Secret
metadata: 
  name: app-secret
type: Opaque
stringData:             # plaintext here — Kubernetes encodes it automatically
  DB_PASSWORD: "vishal123"
  API_KEY: "vishalsapikey123"