apiVersion: v1
kind: ConfigMap
metadata:
  name: flask-config
data: 
  APP_ENV: "production"
  DB_HOST: "postgres-service"
  DB_PORT: "5432"
---
apiVersion: v1
kind: Secret
metadata:
  name: flask-secret
type : Opaque
stringData: 
  DB_PASSWORD: "prod-db-password"
  API_KEY: "flask-secret-key-xyz"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-deployment
spec: 
  replicas: 2
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec: 
      containers:
        - name: flask
          image: flask-configmap-demo:v1
          imagePullPolicy: Never
          envFrom:
            - configMapRef:
                name: flask-config
          env: 
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: flask-secret
                  key: DB_PASSWORD
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: flask-secret
                  key: SECRET_KEY
          ports: 
            - containerPort: 5432       
